In [6]:
import numpy as np
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [7]:
type(a1)

numpy.ndarray

In [9]:
a2 =np.array([[1,2,3],[4,5,6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
a3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [11]:
a1.ndim,a2.ndim,a3.ndim

(1, 2, 3)

In [12]:
a1.size,a2.size,a3.size

(3, 6, 9)

In [13]:
import pandas as pd

df = pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6