In [6]:
import numpy as np
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [7]:
type(a1)

numpy.ndarray

In [9]:
a2 =np.array([[1,2,3],[4,5,6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
a3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [11]:
a1.ndim,a2.ndim,a3.ndim

(1, 2, 3)

In [12]:
a1.size,a2.size,a3.size

(3, 6, 9)

In [13]:
import pandas as pd

df = pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6

In [1]:
##CREATING ARRAY 
import numpy as np


sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [3]:
sample_array.dtype

dtype('int64')

In [4]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [5]:
ones.dtype

dtype('float64')

In [6]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [7]:
random_array = np.random.randint(0,10,size=(3,5))
random_array

array([[4, 5, 1, 8, 5],
       [6, 3, 2, 7, 7],
       [0, 1, 8, 5, 5]], dtype=int32)

In [8]:
random_array.size

15

In [9]:
random_array.shape

(3, 5)

In [10]:
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.17793042, 0.08834526, 0.61953646],
       [0.03164076, 0.50309797, 0.69350349],
       [0.34376643, 0.59153789, 0.61774632],
       [0.70972088, 0.18300851, 0.4168447 ],
       [0.89927769, 0.90968384, 0.71573832]])

In [18]:
np.random.seed(7)

random_array_4 = np.random.random((5, 3))
random_array_4

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [22]:
## 3. Matrecis
np.unique(random_array)

array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int32)

In [25]:
a4 = np.random.randint(10, size=(2,3,4,5))
a4

array([[[[3, 5, 8, 8, 7],
         [5, 0, 0, 2, 8],
         [9, 6, 4, 9, 7],
         [3, 3, 8, 3, 0]],

        [[1, 0, 0, 6, 7],
         [7, 9, 3, 0, 7],
         [7, 7, 0, 5, 4],
         [3, 1, 3, 1, 3]],

        [[4, 3, 1, 9, 5],
         [9, 1, 2, 3, 2],
         [2, 5, 7, 3, 0],
         [9, 9, 3, 4, 5]]],


       [[[3, 0, 4, 8, 6],
         [7, 2, 7, 3, 8],
         [6, 6, 5, 6, 5],
         [7, 1, 5, 4, 4]],

        [[9, 9, 0, 6, 2],
         [6, 8, 2, 4, 1],
         [6, 1, 5, 1, 6],
         [9, 8, 6, 5, 9]],

        [[7, 5, 4, 9, 6],
         [8, 1, 5, 5, 8],
         [3, 7, 7, 9, 4],
         [7, 5, 9, 6, 2]]]], dtype=int32)

In [26]:
a4.shape , a4.ndim

((2, 3, 4, 5), 4)

In [27]:
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [28]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [29]:
a1 + ones

array([2., 3., 4.])

In [30]:
a2 =np.array([[1,2,3],[4,5,6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
a3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [32]:
a1 / ones

array([1., 2., 3.])

In [33]:
a2 /a1

array([[1. , 1. , 1. ],
       [4. , 2.5, 2. ]])

In [34]:
a2 // a1

array([[1, 1, 1],
       [4, 2, 2]])

In [35]:
a2 **2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [37]:
np.square(a2)
a2

array([[1, 2, 3],
       [4, 5, 6]])